### ISSUE TITLE
座標の丸め

### ISSUE THREAD

**Issue by szc126** [kurgm/kage-editor#1]
1. 部品をリサイズ→左下に表示されている座標が `xxx.xxxxx, yyy.yyyyy` みたいな数字になる
1. 良しとして「編集終了」
1. GlyphWiki のテキストボックスが真っ白。君のグリフはもうこの世界にいない。

VS

1. 部品をリサイズ→座標が `xxx.xxxxx, yyy.yyyyy` みたいな数字になる
1. 再び部品をクリックして選択すれば座標が丸められる
1. 良しとして「編集終了」
1. GlyphWiki のテキストボックスは普通

テキストボックスが真っ白になるのは GlyphWiki 側の問題だそうですが（ https://glyphwiki.org/wiki/sandbox?action=preview&textbox=99:0:0:0:0:150:150.0:u90e8 ）、ユーザーのグリフデータが消えるのは望ましくなかろう。

**Comment by kurgm** [comment]
報告ありがとうございます。実際に問題を確認しました。修正します。
