### ISSUE TITLE
Add Strokes Limit

### ISSUE THREAD

**Issue by Hulenkius** [kurgm/kage-editor#16]
When working on some complex charactors, a limit to the strokes is nessesary.
Without a limit, the whole work would be lost after clicking the 編集終了 button.

In the traditional flash editor, there was a limit, which is worth to bring back.

**Comment by liuxilu** [comment]
Better prompting the result, I think.
Is it limited by url length?

**Comment by szc126** [comment]
The restriction is serverside, and all of the data is still present in the URL.
