### ISSUE TITLE
Direction of KAGE engine

### ISSUE THREAD

**Issue by hfhchan** [kurgm/kage-editor#6]
The original KAGE engine by @kamichikoichi hasn't been updated for 2 years.  Will your fork be a purely TypeScript version of KAGE engine, or do you plan on maintaining the updated KAGE engine?

Meanwhile, I have come across numerous KAGE engine edge cases which I would like to change but have not much luck experimenting with code.  I wonder if you may be interested in fixing them in your fork and whether Kamichi-san may be interested in integrating them back into GlyphWiki.

**Comment by hfhchan** [comment]
First one is regarding the Right-top corner of u4e41 (乁), a pull request to add new prefix style was submitted 4 years ago but not merged:
https://github.com/kamichikoichi/kage-engine/pull/2/files

**Comment by hfhchan** [comment]
Another one is stroke thinning with stroke type 2 and hook (suffix 4):
<img src="https://user-images.githubusercontent.com/8191296/87244361-466a3180-c46f-11ea-8347-25920301d73f.png" width=250>
(http://glyphwiki.org/wiki/hkcs_m99ac-p01-s11)

When setting the shrink value on the stroke suffix code, e.g. change 4 to 2004, the following part is incorrectly thinned out instead:
<img src="https://user-images.githubusercontent.com/8191296/87244408-9fd26080-c46f-11ea-9f6a-d9685135f5c6.png" width=250>
I think the logic for thinning the stroke suffix has been accidentally reversed.

**Comment by kurgm** [comment]
The main purpose of this fork is to make the KAGE engine available in modern JavaScript ecosystems. I intend to keep the behavior of the engine (i.e., generated glyph shape of any data) sync with that on the GlyphWiki server. ([The new glyph editor I have created](https://github.com/kurgm/kage-editor) uses the code of this repo, and inconsistency of the glyph shapes may confuse the user.)
To change the behavior, I follow these steps:

1. Submit a bugfix pull request to [the original repo](https://github.com/kamichikoichi/kage-engine)
2. Wait for the pull request to be merged
3. Apply the bugfix patch to this repo

So, for the first case you mentioned, it's still under step 2, and I'm not going to merge that to this repo now.

For the second case, I'm going to investigate it.

**Comment by kurgm** [comment]
It may be a good idea to implement the features not yet merged as “preview features” and allowing the users to enable those features by selecting a checkbox.

**Comment by kurgm** [comment]
Now that the both problems are resolved, I’m closing this issue now.
